version: '3.7'
services:

  postgres:
    image: postgres:14-alpine
    container_name: datagen-postgres
    hostname: datagen-postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=datagen
      - POSTGRES_DB_SCHEMA=datagen

  mongo:
    image: mongo:5.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  api:
    image: datagen
    container_name: datagen
    hostname: datagen
    restart: on-failure
    ports:
      - "8080:8080"